name: example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  get_server: ^1.0.0
  database: ^0.3.3
  orm:
    path: ../../orm

  database_adapter_mysql:
    path: ../../database/adapters/mysql

#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
